name: Update CHANGELOG.md

on:
  push:
    branches:
      - 'v5'
    paths-ignore:
      - '.vscode/**'
      - '**/*.md'

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate full changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Generate changelog for latest commits
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --unreleased --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit
        run: |
          git checkout v4
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "ci(id${{ github.run_id }}): update changelog" -m "${{ steps.git-cliff.outputs.content }}"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/27rogi/website.git v5
